export const mockExamCategories = [
  {
    exam: "Railway",
    totalTests: 42,
    freeTests: 12,
    paidTests: 30,
    duration: "60-90 min",
    difficulty: "Exam Level",
    pattern: "CBT pattern",
    sections: "Maths, Reasoning, GK"
  },
  {
    exam: "SSC",
    totalTests: 1119,
    freeTests: 1037,
    paidTests: 0,
    duration: "60 min",
    difficulty: "Moderate",
    pattern: "Tier pattern",
    sections: "Quant, Reasoning, English, GS"
  },
  {
    exam: "Banking",
    totalTests: 36,
    freeTests: 8,
    paidTests: 28,
    duration: "60-120 min",
    difficulty: "Sectional",
    pattern: "Prelims + mains",
    sections: "Quant, Reasoning, English"
  },
  {
    exam: "Police",
    totalTests: 24,
    freeTests: 6,
    paidTests: 18,
    duration: "90 min",
    difficulty: "State Level",
    pattern: "State police pattern",
    sections: "Reasoning, GK, Maths"
  },
  {
    exam: "Teaching",
    totalTests: 28,
    freeTests: 7,
    paidTests: 21,
    duration: "150 min",
    difficulty: "TET Level",
    pattern: "TET pattern",
    sections: "CDP, Language, Maths, EVS"
  },
  {
    exam: "State Exams",
    totalTests: 31,
    freeTests: 9,
    paidTests: 22,
    duration: "90-120 min",
    difficulty: "Mixed",
    pattern: "State exam pattern",
    sections: "GK, Reasoning, Maths, Hindi"
  }
];

export const timerFeatureList = [
  "Full test countdown with sticky timer",
  "Section-wise timing ready",
  "10 min and 5 min warning states",
  "Auto-submit behavior when time ends",
  "No pause during live test mode",
  "Refresh-safe timing guidance"
];

export const resultAnalysisList = [
  "Score, correct, wrong and unattempted summary",
  "Accuracy, time taken, rank and percentile",
  "Section-wise performance view",
  "Solution and explanation support",
  "Weak topic analysis for next practice"
];

export const mockInterfaceActions = [
  "Save & Next",
  "Mark for Review",
  "Clear Response",
  "Previous",
  "Submit Test",
  "Question Palette"
];

export const sscCglFreeMockSourceUrl = "/mock-tests/free-practice";
export const rojgarWithAnkitQuizSourceUrl = "/mock-tests/free-practice";

export const sscCglAdvancedMocks = [
  {
    id: "ssc-cgl-2026-tier-1-free-hub",
    title: "SSC CGL 2026 Tier 1 - Free Test Hub",
    examName: "SSC CGL",
    questions: 100,
    marks: 200,
    duration: "60 min",
    sectionTiming: "Single full-test timer",
    negativeMarking: "0.50 mark",
    language: "Hindi + English",
    examMode: "Full Test",
    accessType: "Free",
    difficulty: "Exam Level",
    resultVisibility: "Instant on BadamClasses",
    sourceName: "BadamClasses Original",
    testUrl: sscCglFreeMockSourceUrl,
    status: "published",
    featured: true,
    summary: "Professional SSC CGL Tier 1 practice hub with free full-length and previous-year test access."
  },
  {
    id: "ssc-cgl-free-mock-full-tests",
    title: "SSC CGL Free Mock Tests - 82 Test Series",
    examName: "SSC CGL",
    questions: 100,
    marks: 200,
    duration: "60 min",
    sectionTiming: "Single full-test timer",
    negativeMarking: "0.50 mark",
    language: "Hindi + English",
    examMode: "Mock + Sectional",
    accessType: "Free",
    difficulty: "Moderate to Exam Level",
    resultVisibility: "Instant on BadamClasses",
    sourceName: "BadamClasses Original",
    testUrl: sscCglFreeMockSourceUrl,
    status: "published",
    groupLabel: "82 free mock tests",
    summary: "Includes full tests, latest tests, test bucket practice and subject-wise sectional tests."
  },
  {
    id: "ssc-cgl-previous-year-full-tests",
    title: "SSC CGL Previous Year Full Tests - 213 Sets",
    examName: "SSC CGL Previous Year",
    questions: 100,
    marks: 200,
    duration: "60 min",
    sectionTiming: "Single full-test timer",
    negativeMarking: "0.50 mark",
    language: "Hindi + English",
    examMode: "Previous Year Full Test",
    accessType: "Free",
    difficulty: "Actual Exam",
    resultVisibility: "Instant on BadamClasses",
    sourceName: "BadamClasses Original",
    testUrl: sscCglFreeMockSourceUrl,
    status: "published",
    groupLabel: "213 previous-year full tests",
    summary: "Year-wise SSC CGL previous-year full tests from 2019 to 2025."
  },
  {
    id: "ssc-cgl-previous-year-sectional-tests",
    title: "SSC CGL Previous Year Sectional - 824 Sets",
    examName: "SSC CGL Sectional",
    questions: 25,
    marks: 50,
    duration: "15 min",
    sectionTiming: "Section-wise timer",
    negativeMarking: "0.50 mark",
    language: "Hindi + English",
    examMode: "Previous Year Sectional",
    accessType: "Free",
    difficulty: "Topic-wise Exam Level",
    resultVisibility: "Instant on BadamClasses",
    sourceName: "BadamClasses Original",
    testUrl: sscCglFreeMockSourceUrl,
    status: "published",
    groupLabel: "824 sectional tests",
    summary: "Reasoning, Quantitative, English and General Awareness sectional previous-year practice."
  },
  {
    id: "ssc-cgl-2025-previous-year",
    title: "SSC CGL Previous Year 2025 - 46 Full Tests",
    examName: "SSC CGL 2025",
    questions: 100,
    marks: 200,
    duration: "60 min",
    sectionTiming: "Single full-test timer",
    negativeMarking: "0.50 mark",
    language: "Hindi + English",
    examMode: "Year-wise Previous Paper",
    accessType: "Free",
    difficulty: "Actual Exam",
    resultVisibility: "Instant on BadamClasses",
    sourceName: "BadamClasses Original",
    testUrl: sscCglFreeMockSourceUrl,
    status: "published",
    groupLabel: "2025",
    summary: "Latest SSC CGL previous-year full test practice set."
  },
  {
    id: "ssc-cgl-2024-previous-year",
    title: "SSC CGL Previous Year 2024 - 36 Full Tests",
    examName: "SSC CGL 2024",
    questions: 100,
    marks: 200,
    duration: "60 min",
    sectionTiming: "Single full-test timer",
    negativeMarking: "0.50 mark",
    language: "Hindi + English",
    examMode: "Year-wise Previous Paper",
    accessType: "Free",
    difficulty: "Actual Exam",
    resultVisibility: "Instant on BadamClasses",
    sourceName: "BadamClasses Original",
    testUrl: sscCglFreeMockSourceUrl,
    status: "published",
    groupLabel: "2024",
    summary: "SSC CGL 2024 previous-year full tests for real exam practice."
  },
  {
    id: "ssc-cgl-2023-previous-year",
    title: "SSC CGL Previous Year 2023 - 39 Full Tests",
    examName: "SSC CGL 2023",
    questions: 100,
    marks: 200,
    duration: "60 min",
    sectionTiming: "Single full-test timer",
    negativeMarking: "0.50 mark",
    language: "Hindi + English",
    examMode: "Year-wise Previous Paper",
    accessType: "Free",
    difficulty: "Actual Exam",
    resultVisibility: "Instant on BadamClasses",
    sourceName: "BadamClasses Original",
    testUrl: sscCglFreeMockSourceUrl,
    status: "published",
    groupLabel: "2023",
    summary: "SSC CGL 2023 full previous-year test practice."
  },
  {
    id: "ssc-cgl-2022-previous-year",
    title: "SSC CGL Previous Year 2022 - 41 Full Tests",
    examName: "SSC CGL 2022",
    questions: 100,
    marks: 200,
    duration: "60 min",
    sectionTiming: "Single full-test timer",
    negativeMarking: "0.50 mark",
    language: "Hindi + English",
    examMode: "Year-wise Previous Paper",
    accessType: "Free",
    difficulty: "Actual Exam",
    resultVisibility: "Instant on BadamClasses",
    sourceName: "BadamClasses Original",
    testUrl: sscCglFreeMockSourceUrl,
    status: "published",
    groupLabel: "2022",
    summary: "SSC CGL 2022 full previous-year test practice."
  },
  {
    id: "ssc-cgl-2021-previous-year",
    title: "SSC CGL Previous Year 2021 - 21 Full Tests",
    examName: "SSC CGL 2021",
    questions: 100,
    marks: 200,
    duration: "60 min",
    sectionTiming: "Single full-test timer",
    negativeMarking: "0.50 mark",
    language: "Hindi + English",
    examMode: "Year-wise Previous Paper",
    accessType: "Free",
    difficulty: "Actual Exam",
    resultVisibility: "Instant on BadamClasses",
    sourceName: "BadamClasses Original",
    testUrl: sscCglFreeMockSourceUrl,
    status: "published",
    groupLabel: "2021",
    summary: "SSC CGL 2021 full previous-year test practice."
  },
  {
    id: "ssc-cgl-2020-previous-year",
    title: "SSC CGL Previous Year 2020 - 18 Full Tests",
    examName: "SSC CGL 2020",
    questions: 100,
    marks: 200,
    duration: "60 min",
    sectionTiming: "Single full-test timer",
    negativeMarking: "0.50 mark",
    language: "Hindi + English",
    examMode: "Year-wise Previous Paper",
    accessType: "Free",
    difficulty: "Actual Exam",
    resultVisibility: "Instant on BadamClasses",
    sourceName: "BadamClasses Original",
    testUrl: sscCglFreeMockSourceUrl,
    status: "published",
    groupLabel: "2020",
    summary: "SSC CGL 2020 full previous-year test practice."
  },
  {
    id: "ssc-cgl-2019-previous-year",
    title: "SSC CGL Previous Year 2019 - 12 Full Tests",
    examName: "SSC CGL 2019",
    questions: 100,
    marks: 200,
    duration: "60 min",
    sectionTiming: "Single full-test timer",
    negativeMarking: "0.50 mark",
    language: "Hindi + English",
    examMode: "Year-wise Previous Paper",
    accessType: "Free",
    difficulty: "Actual Exam",
    resultVisibility: "Instant on BadamClasses",
    sourceName: "BadamClasses Original",
    testUrl: sscCglFreeMockSourceUrl,
    status: "published",
    groupLabel: "2019",
    summary: "SSC CGL 2019 full previous-year test practice."
  }
];

export const rojgarWithAnkitFreeMocks = [
  {
    id: "rwa-ssc-cgl-mini-mock-2026",
    title: "SSC CGL Mini Mock 2026",
    examName: "SSC CGL",
    questions: 100,
    marks: 200,
    duration: "60 min",
    sectionTiming: "Single full-test timer",
    negativeMarking: "0.50 mark",
    language: "Hindi + English",
    examMode: "Mini Mock",
    accessType: "Free",
    difficulty: "Exam Level",
    resultVisibility: "On BadamClasses",
    sourceName: "BadamClasses Original",
    testUrl: rojgarWithAnkitQuizSourceUrl,
    status: "published",
    groupLabel: "Free Weekly Test",
    summary: "SSC CGL 2026 mini mock practice from the BadamClasses Original free weekly quiz series."
  },
  {
    id: "rwa-ssc-gd-2026",
    title: "SSC GD 2026",
    examName: "SSC GD",
    questions: 80,
    marks: 160,
    duration: "60 min",
    sectionTiming: "Single full-test timer",
    negativeMarking: "0.25 mark",
    language: "Hindi + English",
    examMode: "Mini Mock",
    accessType: "Free",
    difficulty: "Exam Level",
    resultVisibility: "On BadamClasses",
    sourceName: "BadamClasses Original",
    testUrl: rojgarWithAnkitQuizSourceUrl,
    status: "published",
    groupLabel: "Free Weekly Test",
    summary: "SSC GD 2026 free weekly mock for speed, accuracy and exam pattern practice."
  },
  {
    id: "rwa-rrb-group-d-mini-mock-2026",
    title: "RRB Group D Mini Mock 2026",
    examName: "Railway Group D",
    questions: 100,
    marks: 100,
    duration: "90 min",
    sectionTiming: "Single CBT timer",
    negativeMarking: "1/3 mark",
    language: "Hindi + English",
    examMode: "Railway CBT Mini Mock",
    accessType: "Free",
    difficulty: "CBT Level",
    resultVisibility: "On BadamClasses",
    sourceName: "BadamClasses Original",
    testUrl: rojgarWithAnkitQuizSourceUrl,
    status: "published",
    groupLabel: "Free Weekly Test",
    summary: "Railway Group D CBT-style mini mock from the free weekly quiz series."
  },
  {
    id: "rwa-ssc-cgl-tier-1-test-series-2026",
    title: "SSC CGL Tier-1 Test Series 2026",
    examName: "SSC CGL Tier 1",
    questions: 100,
    marks: 200,
    duration: "60 min",
    sectionTiming: "Single full-test timer",
    negativeMarking: "0.50 mark",
    language: "Hindi + English",
    examMode: "Test Series",
    accessType: "Free",
    difficulty: "Exam Level",
    resultVisibility: "On BadamClasses",
    sourceName: "BadamClasses Original",
    testUrl: rojgarWithAnkitQuizSourceUrl,
    status: "published",
    groupLabel: "Free Weekly Test",
    summary: "SSC CGL Tier-1 2026 test series entry for structured full-test practice."
  },
  {
    id: "rwa-ssc-cgl-tier-1-2026",
    title: "SSC CGL Tier-1 2026",
    examName: "SSC CGL Tier 1",
    questions: 100,
    marks: 200,
    duration: "60 min",
    sectionTiming: "Single full-test timer",
    negativeMarking: "0.50 mark",
    language: "Hindi + English",
    examMode: "Full Test",
    accessType: "Free",
    difficulty: "Exam Level",
    resultVisibility: "On BadamClasses",
    sourceName: "BadamClasses Original",
    testUrl: rojgarWithAnkitQuizSourceUrl,
    status: "published",
    groupLabel: "Free Weekly Test",
    summary: "SSC CGL Tier-1 2026 free practice test with full exam-style metadata."
  },
  {
    id: "rwa-ssc-cgl-mock-2026-english-sanjeev-sir",
    title: "SSC CGL Mock 2026 English (Sanjeev Sir)",
    examName: "SSC CGL English",
    questions: 25,
    marks: 50,
    duration: "15 min",
    sectionTiming: "English sectional timer",
    negativeMarking: "0.50 mark",
    language: "English",
    examMode: "Sectional Mock",
    accessType: "Free",
    difficulty: "Sectional",
    resultVisibility: "On BadamClasses",
    sourceName: "BadamClasses Original",
    testUrl: rojgarWithAnkitQuizSourceUrl,
    status: "published",
    groupLabel: "Free Weekly Test",
    summary: "SSC CGL English sectional mock focused on vocabulary, grammar and comprehension speed."
  },
  {
    id: "rwa-ssb-head-constable-mini-mock-2026",
    title: "SSB Head Constable Mini Mock 2026",
    examName: "SSB Head Constable",
    questions: 100,
    marks: 100,
    duration: "120 min",
    sectionTiming: "Single full-test timer",
    negativeMarking: "As per source test",
    language: "Hindi + English",
    examMode: "Mini Mock",
    accessType: "Free",
    difficulty: "Defence Level",
    resultVisibility: "On BadamClasses",
    sourceName: "BadamClasses Original",
    testUrl: rojgarWithAnkitQuizSourceUrl,
    status: "published",
    groupLabel: "Free Weekly Test",
    summary: "SSB Head Constable free mini mock for defence exam practice."
  },
  {
    id: "rwa-ntpc-graduation-cbt-2-mini-mock-2026",
    title: "NTPC Graduation Level (CBT-2) Mini Mock 2026",
    examName: "RRB NTPC CBT-2",
    questions: 120,
    marks: 120,
    duration: "90 min",
    sectionTiming: "Single CBT-2 timer",
    negativeMarking: "1/3 mark",
    language: "Hindi + English",
    examMode: "Railway CBT-2 Mini Mock",
    accessType: "Free",
    difficulty: "CBT-2 Level",
    resultVisibility: "On BadamClasses",
    sourceName: "BadamClasses Original",
    testUrl: rojgarWithAnkitQuizSourceUrl,
    status: "published",
    groupLabel: "Free Weekly Test",
    summary: "Railway NTPC Graduation Level CBT-2 mini mock for higher-level practice."
  },
  {
    id: "rwa-navodaya-vidyalaya-test",
    title: "Navodaya Vidyalaya Test",
    examName: "Navodaya Vidyalaya",
    questions: 100,
    marks: 100,
    duration: "120 min",
    sectionTiming: "Single full-test timer",
    negativeMarking: "As per source test",
    language: "Hindi + English",
    examMode: "Teaching/School Exam Test",
    accessType: "Free",
    difficulty: "Teaching Level",
    resultVisibility: "On BadamClasses",
    sourceName: "BadamClasses Original",
    testUrl: rojgarWithAnkitQuizSourceUrl,
    status: "published",
    groupLabel: "Free Weekly Test",
    summary: "Navodaya Vidyalaya free test entry for teaching and school recruitment practice."
  },
  {
    id: "rwa-editorial-dictionary-2026",
    title: "Editorial Dictionary 2026",
    examName: "English Vocabulary",
    questions: 25,
    marks: 25,
    duration: "15 min",
    sectionTiming: "Vocabulary drill timer",
    negativeMarking: "No fixed penalty",
    language: "English",
    examMode: "Vocabulary Quiz",
    accessType: "Free",
    difficulty: "Daily Practice",
    resultVisibility: "On BadamClasses",
    sourceName: "BadamClasses Original",
    testUrl: rojgarWithAnkitQuizSourceUrl,
    status: "published",
    groupLabel: "Free Weekly Test",
    summary: "Editorial Dictionary 2026 vocabulary quiz for English preparation."
  }
];

export const originalFreePracticeQuestions = [
  {
    id: "q1",
    section: "Quantitative Aptitude",
    question: "If a number is increased by 20% and then decreased by 20%, what is the net percentage change?",
    options: ["4% increase", "4% decrease", "No change", "2% decrease"],
    answer: 1,
    explanation: "Let the number be 100. After 20% increase it becomes 120, then 20% decrease makes it 96. Net change is 4% decrease."
  },
  {
    id: "q2",
    section: "Reasoning",
    question: "In a certain code, BADAM is written as CBEBN. How will CLASS be written in the same code?",
    options: ["DMBTT", "DLCUT", "DKBRT", "DMBSU"],
    answer: 0,
    explanation: "Each letter is shifted one step forward: C->D, L->M, A->B, S->T, S->T."
  },
  {
    id: "q3",
    section: "English",
    question: "Choose the correctly spelt word.",
    options: ["Accomodate", "Acommodate", "Accommodate", "Accommadate"],
    answer: 2,
    explanation: "The correct spelling is Accommodate."
  },
  {
    id: "q4",
    section: "General Awareness",
    question: "The Constitution of India came into effect on which date?",
    options: ["15 August 1947", "26 January 1950", "2 October 1950", "26 November 1949"],
    answer: 1,
    explanation: "The Constitution came into effect on 26 January 1950."
  },
  {
    id: "q5",
    section: "Quantitative Aptitude",
    question: "A train covers 180 km in 3 hours. What is its average speed?",
    options: ["45 km/h", "50 km/h", "60 km/h", "75 km/h"],
    answer: 2,
    explanation: "Average speed = distance / time = 180 / 3 = 60 km/h."
  },
  {
    id: "q6",
    section: "Reasoning",
    question: "Find the next number in the series: 3, 6, 12, 24, 48, ?",
    options: ["72", "84", "96", "108"],
    answer: 2,
    explanation: "Each term is multiplied by 2, so the next term is 96."
  },
  {
    id: "q7",
    section: "English",
    question: "Select the antonym of 'expand'.",
    options: ["Extend", "Increase", "Contract", "Spread"],
    answer: 2,
    explanation: "Contract is the opposite of expand."
  },
  {
    id: "q8",
    section: "General Awareness",
    question: "Which gas is most abundant in Earth's atmosphere?",
    options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"],
    answer: 1,
    explanation: "Nitrogen makes up about 78% of Earth's atmosphere."
  },
  {
    id: "q9",
    section: "Quantitative Aptitude",
    question: "The average of 5, 7, 9, 11 and 13 is:",
    options: ["8", "9", "10", "11"],
    answer: 1,
    explanation: "Sum is 45 and count is 5, so average is 9."
  },
  {
    id: "q10",
    section: "Reasoning",
    question: "If NORTH is coded as OPUI, then SOUTH will be coded as:",
    options: ["TPVUI", "TQVUJ", "TPVTH", "RPVUI"],
    answer: 0,
    explanation: "Each letter is shifted one step forward: S->T, O->P, U->V, T->U, H->I."
  }
];